"""SQLAlchemy tables and tenant-scoped metadata for calibration persistence."""

from __future__ import annotations

from collections.abc import Mapping
from decimal import Decimal
from typing import Any

import sqlalchemy as sa

metadata = sa.MetaData()
JsonScalar = str | float | int | Decimal


def _scope_columns() -> tuple[sa.Column[Any], ...]:
    return (
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("classification", sa.String(64), nullable=False),
    )


def _table(name: str, *columns: sa.Column[Any]) -> sa.Table:
    return sa.Table(name, metadata, *_scope_columns(), *columns, schema="modeling")


linear_viscoelastic_calibration_plan_table = _table(
    "linear_viscoelastic_calibration_plan",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("current_revision_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("idempotency_key", sa.String(255), nullable=True),
    sa.Column("idempotency_digest", sa.CHAR(64), nullable=True),
)
linear_viscoelastic_calibration_plan_revision_table = _table(
    "linear_viscoelastic_calibration_plan_revision",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("aggregate_id", sa.Uuid(), nullable=False),
    sa.Column("revision_no", sa.BigInteger(), nullable=False),
    sa.Column("based_on_revision_id", sa.Uuid(), nullable=True),
    sa.Column("schema_id", sa.String(255), nullable=False),
    sa.Column("schema_version", sa.String(64), nullable=False),
    sa.Column("content_hash", sa.CHAR(64), nullable=False),
    sa.Column("plan_sha256", sa.CHAR(64), nullable=False),
    sa.Column("test_data_id", sa.Uuid(), nullable=False),
    sa.Column("test_data_revision_id", sa.Uuid(), nullable=False),
    sa.Column("test_data_sha256", sa.CHAR(64), nullable=True),
    sa.Column("canonical_artifact_id", sa.Uuid(), nullable=False),
    sa.Column("canonical_artifact_sha256", sa.CHAR(64), nullable=False),
    sa.Column("canonical_artifact_media_type", sa.String(255), nullable=True),
    sa.Column("normalized_artifact_id", sa.Uuid(), nullable=False),
    sa.Column("normalized_artifact_sha256", sa.CHAR(64), nullable=False),
    sa.Column("normalized_artifact_media_type", sa.String(255), nullable=True),
    sa.Column("raw_source_sha256", sa.CHAR(64), nullable=False),
    sa.Column("import_profile_id", sa.Uuid(), nullable=False),
    sa.Column("import_profile_revision_id", sa.Uuid(), nullable=False),
    sa.Column("profile_sha256", sa.CHAR(64), nullable=False),
    sa.Column("processing_output_id", sa.Uuid(), nullable=True),
    sa.Column("processing_output_revision_id", sa.Uuid(), nullable=True),
    sa.Column("processing_output_sha256", sa.CHAR(64), nullable=True),
    sa.Column("processing_metadata_artifact_id", sa.Uuid(), nullable=True),
    sa.Column("processing_metadata_artifact_sha256", sa.CHAR(64), nullable=True),
    sa.Column("processing_metadata_artifact_media_type", sa.String(255), nullable=True),
    sa.Column("processing_result_artifact_id", sa.Uuid(), nullable=True),
    sa.Column("processing_result_artifact_sha256", sa.CHAR(64), nullable=True),
    sa.Column("processing_result_artifact_media_type", sa.String(255), nullable=True),
    sa.Column("input_semantics", sa.JSON(), nullable=False),
    sa.Column("term_counts", sa.JSON(), nullable=False),
    sa.Column("parameter_bounds", sa.JSON(), nullable=False),
    sa.Column("start_vectors", sa.JSON(), nullable=False),
    sa.Column("objective_policy", sa.JSON(), nullable=False),
    sa.Column("optimizer_policy", sa.JSON(), nullable=False),
    sa.Column("statuses", sa.JSON(), nullable=False),
    sa.Column("plan_payload", sa.JSON(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
    sa.Column("change_reason", sa.Text(), nullable=False),
    sa.Column("request_id", sa.Uuid(), nullable=False),
    sa.Column("trace_id", sa.String(255), nullable=False),
)
linear_viscoelastic_calibration_run_table = _table(
    "linear_viscoelastic_calibration_run",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("plan_id", sa.Uuid(), nullable=False),
    sa.Column("plan_revision_id", sa.Uuid(), nullable=False),
    sa.Column("plan_sha256", sa.CHAR(64), nullable=False),
    sa.Column("job_id", sa.Uuid(), nullable=False),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("terminal_digest", sa.CHAR(64), nullable=True),
    sa.Column("execution_ledger_sha256", sa.CHAR(64), nullable=True),
    sa.Column("failure_code", sa.String(100), nullable=True),
    sa.Column("failure_detail", sa.Text(), nullable=True),
    sa.Column("recovery_hint", sa.String(1000), nullable=True),
    sa.Column("recommendation_id", sa.Uuid(), nullable=True),
    sa.Column("idempotency_key", sa.String(255), nullable=False),
    sa.Column("request_sha256", sa.CHAR(64), nullable=False),
    sa.Column("result_payload", sa.JSON(), nullable=True),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
    sa.Column("request_id", sa.Uuid(), nullable=False),
    sa.Column("trace_id", sa.String(255), nullable=False),
)
linear_viscoelastic_calibration_execution_attempt_table = _table(
    "linear_viscoelastic_calibration_execution_attempt",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("run_id", sa.Uuid(), nullable=False),
    sa.Column("job_id", sa.Uuid(), nullable=False),
    sa.Column("job_attempt_no", sa.Integer(), nullable=False),
    sa.Column("state", sa.String(32), nullable=False),
    sa.Column("failure_code", sa.String(100), nullable=True),
    sa.Column("failure_detail", sa.Text(), nullable=True),
    sa.Column("recovery_hint", sa.String(1000), nullable=True),
    sa.Column("package_id", sa.String(255), nullable=False),
    sa.Column("package_version", sa.String(64), nullable=False),
    sa.Column("package_sha256", sa.CHAR(64), nullable=False),
    sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("result_manifest_artifact_id", sa.Uuid(), nullable=True),
    sa.Column("result_manifest_sha256", sa.CHAR(64), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
)
linear_viscoelastic_calibration_numerical_attempt_table = _table(
    "linear_viscoelastic_calibration_numerical_attempt",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("run_id", sa.Uuid(), nullable=False),
    sa.Column("execution_attempt_id", sa.Uuid(), nullable=False),
    sa.Column("ordinal", sa.Integer(), nullable=False),
    sa.Column("term_count", sa.Integer(), nullable=False),
    sa.Column("start_vector", sa.JSON(), nullable=False),
    sa.Column("transformed_start_vector", sa.JSON(), nullable=False),
    sa.Column("status", sa.Integer(), nullable=False),
    sa.Column("optimizer_message", sa.Text(), nullable=False),
    sa.Column("nfev", sa.Integer(), nullable=False),
    sa.Column("cost", sa.Float(), nullable=False),
    sa.Column("optimality", sa.Float(), nullable=False),
    sa.Column("active_mask", sa.JSON(), nullable=False),
    sa.Column("physical_parameters", sa.JSON(), nullable=False),
    sa.Column("transformed_parameters", sa.JSON(), nullable=False),
    sa.Column("residuals", sa.JSON(), nullable=False),
    sa.Column("residuals_artifact_id", sa.Uuid(), nullable=True),
    sa.Column("objective_history_artifact_id", sa.Uuid(), nullable=True),
    sa.Column("rank_sigma_max", sa.Float(), nullable=False),
    sa.Column("rank_threshold", sa.Float(), nullable=False),
    sa.Column("rank_status", sa.String(32), nullable=False),
    sa.Column("rank_warning_code", sa.String(100), nullable=True),
    sa.Column("objective_history", sa.JSON(), nullable=False),
    sa.Column("rss", sa.Float(), nullable=False),
    sa.Column("rank", sa.Integer(), nullable=False),
    sa.Column("singular_values", sa.JSON(), nullable=False),
    sa.Column("warning_codes", sa.JSON(), nullable=False),
    sa.Column("converged", sa.Boolean(), nullable=False),
    sa.Column("physical", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
)
linear_viscoelastic_calibration_candidate_table = _table(
    "linear_viscoelastic_calibration_candidate",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("run_id", sa.Uuid(), nullable=False),
    sa.Column("numerical_attempt_id", sa.Uuid(), nullable=False),
    sa.Column("attempt_ordinal", sa.Integer(), nullable=False),
    sa.Column("term_count", sa.Integer(), nullable=False),
    sa.Column("candidate_sha256", sa.CHAR(64), nullable=False),
    sa.Column("physical_parameters", sa.JSON(), nullable=False),
    sa.Column("transformed_parameters", sa.JSON(), nullable=False),
    sa.Column("rss", sa.Float(), nullable=False),
    sa.Column("bic", sa.Float(), nullable=False),
    sa.Column("calibration_residuals_artifact_id", sa.Uuid(), nullable=False),
    sa.Column("holdout_residuals_artifact_id", sa.Uuid(), nullable=True),
    sa.Column("calibration_residuals", sa.JSON(), nullable=False),
    sa.Column("holdout_residuals", sa.JSON(), nullable=False),
    sa.Column("rank", sa.Integer(), nullable=False),
    sa.Column("singular_values", sa.JSON(), nullable=False),
    sa.Column("rank_sigma_max", sa.Float(), nullable=False),
    sa.Column("rank_threshold", sa.Float(), nullable=False),
    sa.Column("rank_status", sa.String(32), nullable=False),
    sa.Column("rank_warning_code", sa.String(100), nullable=True),
    sa.Column("warning_codes", sa.JSON(), nullable=False),
    sa.Column("uncertainty_status", sa.String(32), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
)
linear_viscoelastic_calibration_recommendation_table = _table(
    "linear_viscoelastic_calibration_recommendation",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("run_id", sa.Uuid(), nullable=False),
    sa.Column("candidate_id", sa.Uuid(), nullable=False),
    sa.Column("candidate_sha256", sa.CHAR(64), nullable=False),
    sa.Column("recommendation_sha256", sa.CHAR(64), nullable=False),
    sa.Column("rule_version", sa.String(100), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
)
linear_viscoelastic_calibration_selection_table = _table(
    "linear_viscoelastic_calibration_selection",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("current_revision_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("idempotency_key", sa.String(255), nullable=True),
    sa.Column("idempotency_digest", sa.CHAR(64), nullable=True),
)
linear_viscoelastic_calibration_selection_revision_table = _table(
    "linear_viscoelastic_calibration_selection_revision",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("aggregate_id", sa.Uuid(), nullable=False),
    sa.Column("revision_no", sa.BigInteger(), nullable=False),
    sa.Column("based_on_revision_id", sa.Uuid(), nullable=True),
    sa.Column("schema_id", sa.String(255), nullable=False),
    sa.Column("schema_version", sa.String(64), nullable=False),
    sa.Column("content_hash", sa.CHAR(64), nullable=False),
    sa.Column("plan_revision_id", sa.Uuid(), nullable=False),
    sa.Column("run_id", sa.Uuid(), nullable=False),
    sa.Column("candidate_id", sa.Uuid(), nullable=False),
    sa.Column("candidate_sha256", sa.CHAR(64), nullable=False),
    sa.Column("reason", sa.Text(), nullable=False),
    sa.Column("warning_acknowledgements", sa.JSON(), nullable=False),
    sa.Column("actor", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=False),
    sa.Column("change_reason", sa.Text(), nullable=False),
    sa.Column("request_id", sa.Uuid(), nullable=False),
    sa.Column("trace_id", sa.String(255), nullable=False),
    sa.Column("selection_payload", sa.JSON(), nullable=False),
)

TABLES: Mapping[str, sa.Table] = {
    table.name: table
    for table in (
        linear_viscoelastic_calibration_plan_table,
        linear_viscoelastic_calibration_plan_revision_table,
        linear_viscoelastic_calibration_run_table,
        linear_viscoelastic_calibration_execution_attempt_table,
        linear_viscoelastic_calibration_numerical_attempt_table,
        linear_viscoelastic_calibration_candidate_table,
        linear_viscoelastic_calibration_recommendation_table,
        linear_viscoelastic_calibration_selection_table,
        linear_viscoelastic_calibration_selection_revision_table,
    )
}
