"""Stable facade for the linear-viscoelastic calibration domain.

Implementation ownership is split into governed input semantics, explicit calibration policy,
immutable results/evidence, numerical equations, and selection/promotion evidence. Existing
callers continue importing the public domain surface from this module.
"""

__all__ = (
    "EQUAL_PER_POINT_RULE_VERSION",
    "FLOAT64_EPSILON",
    "LINEAR_VISCOELASTIC_BIC_RULE_VERSION",
    "LINEAR_VISCOELASTIC_CALIBRATION_PLAN_SCHEMA_ID",
    "LINEAR_VISCOELASTIC_CALIBRATION_PLAN_SCHEMA_VERSION",
    "LINEAR_VISCOELASTIC_CALIBRATION_RESULT_SCHEMA_ID",
    "LINEAR_VISCOELASTIC_CALIBRATION_RESULT_SCHEMA_VERSION",
    "LINEAR_VISCOELASTIC_MAX_TERM_COUNT",
    "LINEAR_VISCOELASTIC_OBJECTIVE_HISTORY_SCHEMA_ID",
    "LINEAR_VISCOELASTIC_PLUGIN_ID",
    "LINEAR_VISCOELASTIC_PLUGIN_VERSION",
    "LINEAR_VISCOELASTIC_RECOMMENDATION_POLICY",
    "LINEAR_VISCOELASTIC_RESPONSE_RESIDUALS_SCHEMA_ID",
    "LINEAR_VISCOELASTIC_SEED_STATUS",
    "NORMALIZED_ARRAY_EVIDENCE_RULE_VERSION",
    "SELECTED_ARRAY_DIGEST_RULE_VERSION",
    "ArtifactPin",
    "CandidateScopeMode",
    "automatic_candidate_term_counts",
    "calibration_observation_count",
    "maximum_supported_prony_term_count",
    "CalibrationCandidate",
    "CalibrationPartition",
    "CalibrationRecommendation",
    "CalibrationRunResult",
    "CalibrationWeights",
    "CanonicalViscoelasticInput",
    "ChannelAvailability",
    "DataAvailability",
    "DmaObservation",
    "DmaPoint",
    "ExactRevisionPin",
    "ExecutionFailureCode",
    "GovernedViscoelasticInputSemantics",
    "InputChannelSemantics",
    "LinearViscoelasticCalibrationError",
    "LinearViscoelasticCalibrationPlan",
    "LinearViscoelasticChannel",
    "LinearViscoelasticInputError",
    "LinearViscoelasticPlanError",
    "LinearViscoelasticSelection",
    "LinearViscoelasticSelectionError",
    "NumericalAttempt",
    "ObjectiveEvaluation",
    "ParameterBound",
    "PointDisposition",
    "PointPartition",
    "RankDiagnostic",
    "RankStatus",
    "RelaxationObservation",
    "RelaxationPoint",
    "RunStatus",
    "SourceOrdinalDisposition",
    "UncertaintyStatus",
    "calculate_bic",
    "calibrate_linear_viscoelastic",
    "compute_bic",
    "compute_rank_diagnostic",
    "compute_selected_arrays_digest",
    "evaluate_dma_loss_modulus",
    "evaluate_dma_moduli",
    "evaluate_dma_storage_modulus",
    "evaluate_relaxation_modulus",
    "fit_linear_viscoelastic",
    "normalized_arrow_float64_to_numpy_evidence",
    "promote_selected_linear_viscoelastic_candidate",
    "rank_diagnostic",
    "recommend_candidate",
    "selected_arrays_digest",
    "selected_arrays_digest_bytes",
    "selection_acknowledgement",
)

from cmp.modules.modeling.domain.linear_viscoelastic_contracts import (
    EQUAL_PER_POINT_RULE_VERSION,
    FLOAT64_EPSILON,
    LINEAR_VISCOELASTIC_BIC_RULE_VERSION,
    LINEAR_VISCOELASTIC_CALIBRATION_PLAN_SCHEMA_ID,
    LINEAR_VISCOELASTIC_CALIBRATION_PLAN_SCHEMA_VERSION,
    LINEAR_VISCOELASTIC_CALIBRATION_RESULT_SCHEMA_ID,
    LINEAR_VISCOELASTIC_CALIBRATION_RESULT_SCHEMA_VERSION,
    LINEAR_VISCOELASTIC_MAX_TERM_COUNT,
    LINEAR_VISCOELASTIC_OBJECTIVE_HISTORY_SCHEMA_ID,
    LINEAR_VISCOELASTIC_PLUGIN_ID,
    LINEAR_VISCOELASTIC_PLUGIN_VERSION,
    LINEAR_VISCOELASTIC_RECOMMENDATION_POLICY,
    LINEAR_VISCOELASTIC_RESPONSE_RESIDUALS_SCHEMA_ID,
    LINEAR_VISCOELASTIC_SEED_STATUS,
    NORMALIZED_ARRAY_EVIDENCE_RULE_VERSION,
    SELECTED_ARRAY_DIGEST_RULE_VERSION,
    CalibrationPartition,
    CandidateScopeMode,
    DataAvailability,
    ExecutionFailureCode,
    LinearViscoelasticCalibrationError,
    LinearViscoelasticChannel,
    LinearViscoelasticInputError,
    LinearViscoelasticPlanError,
    LinearViscoelasticSelectionError,
    PointPartition,
    RankStatus,
    RunStatus,
    SourceOrdinalDisposition,
    UncertaintyStatus,
)
from cmp.modules.modeling.domain.linear_viscoelastic_input import (
    ArtifactPin,
    CanonicalViscoelasticInput,
    ChannelAvailability,
    DmaObservation,
    DmaPoint,
    ExactRevisionPin,
    GovernedViscoelasticInputSemantics,
    InputChannelSemantics,
    PointDisposition,
    RelaxationObservation,
    RelaxationPoint,
)
from cmp.modules.modeling.domain.linear_viscoelastic_numerical import (
    calculate_bic,
    calibrate_linear_viscoelastic,
    evaluate_dma_loss_modulus,
    evaluate_dma_moduli,
    evaluate_dma_storage_modulus,
    evaluate_relaxation_modulus,
    rank_diagnostic,
    recommend_candidate,
)
from cmp.modules.modeling.domain.linear_viscoelastic_policy import (
    CalibrationWeights,
    LinearViscoelasticCalibrationPlan,
    ParameterBound,
    automatic_candidate_term_counts,
    calibration_observation_count,
    maximum_supported_prony_term_count,
)
from cmp.modules.modeling.domain.linear_viscoelastic_results import (
    CalibrationCandidate,
    CalibrationRecommendation,
    CalibrationRunResult,
    NumericalAttempt,
    ObjectiveEvaluation,
    RankDiagnostic,
)
from cmp.modules.modeling.domain.linear_viscoelastic_selection import (
    LinearViscoelasticSelection,
    compute_selected_arrays_digest,
    normalized_arrow_float64_to_numpy_evidence,
    promote_selected_linear_viscoelastic_candidate,
    selected_arrays_digest,
    selected_arrays_digest_bytes,
    selection_acknowledgement,
)

# Historical aliases remain explicit at the facade while implementation ownership stays in the
# numerical module.
fit_linear_viscoelastic = calibrate_linear_viscoelastic
compute_bic = calculate_bic
compute_rank_diagnostic = rank_diagnostic
